name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari pukul 00:00 UTC
  push:
    branches:
      - main

jobs:
  generate_snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Fransis96/action@main # Gunakan Action dari repo Anda
        with:
          github_user_name: Fransis96
          outputs: |
            dark.svg?palette=github-dark&color_snake=blue
            light.svg?color_snake=#7845ab

      - name: Push Snake Animation
        run: |
          git config --global user.name "Fransis96"
          git config --global user.email "fransiskus.agustinus@students.utdi.ac.id"
          git add .
          git commit -m "Update Snake Animation"
          git push
