name: Generate Snake Game from Contributions Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan sekali setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run Snake Game Action
        uses: ./action.yml
        with:
          github_user_name: Fransis96
          outputs: |
            snake.svg?palette=github&color_snake=blue
