name: Generate Snake Game from Contributions Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan sekali setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate Snake Game
        run: |
          curl -O https://raw.githubusercontent.com/Platane/snk/main/snake.js
          node snake.js --username Fransis96 --output dist/snake.svg

      - name: Upload Snake Game
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/snake.svg
