name: Generate Snake Animation

on:
  # Jalankan setiap push ke branch `main` atau setiap hari pukul 00:00 UTC
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate_snake:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Fransis96

      # Commit and push snake.svg ke branch `main`
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "Fransis96"
          git config --global user.email "fransiskus.agustinus@students.utdi.ac.id"
          mv github-contribution-grid-snake.svg snake.svg
          git add snake.svg
          git commit -m "Update snake animation"
          git push
