# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake
# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake  
      - uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: Fransis96

      # Show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Upload the generated snake as an artifact
      - name: Upload Snake GIF
        uses: actions/upload-artifact@v3
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.gif

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: snake-svg
          path: dist/github-contribution-grid-snake.svg
