name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: Fransis96
          gif_out_path: dist/snake.gif

      - name: Push Snake Game to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main
          force: true
